# Generated by Django 4.1.1 on 2022-09-24 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_corporate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='corporate_id',
            field=models.ForeignKey(default='Global', on_delete=django.db.models.deletion.CASCADE, to='core.corporateuser'),
        ),
    ]
